import Menu from "@/components/elements/menu";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Gestão de Vendas",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="pt-br">
            <body className={inter.className + " flex mt-8"}>
                <header>
                    <Menu />
                </header>
                <main className={"block mx-auto w-3/6"}>{children}</main>
            </body>
        </html>
    );
}
